### ISSUE TITLE
Neo4j runtime detection - no option to add local - offers to download windows installer

### ISSUE THREAD

**Issue by magick93** [neo4emf/Neo4EMF#14]
I am prompted to download Neo4j runtime. I already have it installed locally, however I do not get the option to use my locally installed runtime. 

Also, I am using linux, and the only option I get in the wizard is to download a windows version of the Neo4j runtime.
![selection_084](https://cloud.githubusercontent.com/assets/2173213/6310857/27f613d2-b9c0-11e4-8b66-77f994c4bf47.png)

![selection_085](https://cloud.githubusercontent.com/assets/2173213/6310858/2d83a2ba-b9c0-11e4-9b0b-34598fcb52ae.png)

**Comment by abelgomez** [comment]
Hello @magick93,

although the URL suggests that the runtime is for windows systems only, this is not the case. The wizard downloads the package and extracts the files in the "lib" folder building an OSGi bundle dynamically. The files in the lib folder are platform independent. Thats why the selection list only shows "Neo4J 1.9.4 Runtime" and not "Neo4J 1.9.4 Runtime for Windows" or "Neo4J 1.9.4 Runtime for Linux".

Since Neo4j packages their binary files in platform dependent JARs (for the server launch scripts) we had to choose one.

Regarding the use of your local environment, we don't provide out-of-the-box support for that, since Neo4EMF needs the Neo4j environment to be packaged as an OSGi bundle. Since Neo4EMF uses Neo4j in embedded mode, we considered that downloading a specific version was fair enough. Distributing the Neo4j binaries is a bit tricky because of the incompatibility between the Neo4EMF and Neo4j licenses. We only provide the installer for Neo4j 1.94 since the 2.X branch has not been tested with Neo4EMF.
